### ISSUE TITLE
Review [Round 2]: remove extraneous files

### ISSUE THREAD

**Issue by cthoyt** [r-costa/sbml2hyb#13]
Several files seem to be committed to the repository that make navigating it confusing. Please delete the following directories and add them to a `.gitignore` file so they don't get accidentally committed again. You can make a base `.gitignore` file with https://www.toptal.com/developers/gitignore/. Here's a good starting point: https://www.toptal.com/developers/gitignore/api/python,intellij,pycharm,jupyternotebooks,windows,macos,vim

- the `dist/` directory should be deleted (in general, build artifacts get sent to places like PyPI, not kept in version control)
- same for `src/sbml2hyb.egg-info`
- `src/__init__.py` is not necessary. You only need this inside `src/sbml2hyb/` and sub-modules
- There appear to be duplicate python files inside `windows_exe/` of the packaged files.

**Comment by r-costa** [comment]
Done.
